" set the runtime path to include Vundle and initialize
set path+=.,~/
set rtp+=~/.vim/bundle/Vundle.vim

function! M_Setup()
    hi CursorLine cterm=NONE ctermbg=234 ctermfg=darkgreen
    filetype plugin indent on
    syntax on
    set expandtab mouse=a nu nocompatible cindent laststatus=2 cursorline
    set incsearch hlsearch showmatch matchtime=1 hidden t_Co=256 autochdir
    set clipboard+=unnamed encoding=utf-8 termencoding=utf-8 fileencodings=utf-8,gbk
    set formatoptions+=mM textwidth=110 fencs=utf-8,gbk backspace=indent,eol,start
    set wildignore+=node_modules,.git,*.o,*.obj,vendor 
    map ,dt a<C-R>=strftime('%Y-%m-%d %H:%M')<CR>
    no<c-k> <c-w>k
    no<c-j> <c-w>j 
    no<c-h> <c-w>h
    no<c-l> <c-w>l
    nnoremap tt :sh<cr>
    nnoremap nt :NERDTreeToggle<CR>
    nnoremap ct :CommandT<CR>
    nnoremap tl :TagbarToggle<CR>   "设置快捷键  
    nnoremap H :set cursorline!<CR>
    nnoremap r :source $MYVIMRC<CR>
    nnoremap z $a
    nnoremap f 0i
    inoremap <esc> <nop>
    inoremap jj <esc>

    let &termencoding=&encoding
    let g:vim_markdown_folding_disabled=1
    let g:html_diff_one_file = 0
    let g:html_number_lines = 0
    let g:CommandTMaxFiles = 10000
    let g:formatterpath = ['~/.vim/template/']
    let g:airline_theme='aurora'
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#left_sep = ' '
    let g:airline#extensions#tabline#left_alt_sep = '>' 
    let g:airline#extensions#branch#enabled = 1
    let g:airline#extensions#tabline#buffer_nr_show = 1
    let g:airline#extensions#tabline#fnamemod = ':t'
    let g:tagbar_width = 30
    let g:tagbar_right = 1
    let NERDTreeWinSize=35
    let NERDChristmasTree=1
    " let g:syntastic_javascript_checkers = ['eslint']
    
    " let Vundle manage Vundle, required
    Plugin 'majutsushi/tagbar'
    Plugin 'wincent/command-t'
    Plugin 'scrooloose/nerdtree'
    Plugin 'plasticboy/vim-markdown'
    Plugin 'Chiel92/vim-autoformat'
    Plugin 'Raimondi/delimitMate'
    Plugin 'nathanaelkane/vim-indent-guides'
    Plugin 'tmux-plugins/vim-tmux'
    Plugin 'posva/vim-vue'
    Plugin 'tpope/vim-fugitive'
    Plugin 'vim-airline/vim-airline'
    Plugin 'vim-airline/vim-airline-themes'
    Plugin 'airblade/vim-gitgutter'
    Plugin 'scrooloose/syntastic'


endfunction

function! RunRubyP()
    let ftp = &filetype
    if ftp=='ruby'
        exe ":!ruby ./%"
    endif
endfunction

function! WithHobbies()
    " only set 2 space width for javascript, 4 for else.
    let ft = &filetype
    if ft =="javascript"
        set shiftwidth=2
        set tabstop=2
        set softtabstop=2
    else
        set shiftwidth=4
        set tabstop=4
        set softtabstop=4
    endif
endfunction

function! Comment() 
    let comment_indicator = '//'
    let wordUnderCursor = expand('<cword>')
    let line = getline('.')
    let commentline = line
    let nu = stridx(line, comment_indicator)
    if nu == 0
        let commentline = strpart(line, 2)
    else
        let commentline = '//' . line
    endif
    call setline('.', commentline)
endfunction



function! My_abbreviates()
     abbr mtb \| Tables   \| Are           \| Cool  \|<cr>\| -------- \|:-------------:\| -----:\|<cr>\| col 3 is \| right-aligned \| $1600 \|<cr>
endfunction

function! Auto_save()
    if &filetype != 'nerdtree' && &filetype != 'tagbar'
        write
    endif
endfunction

call vundle#begin()
call pathogen#infect()

call M_Setup()
call My_abbreviates()
nnoremap bb :call RunRubyP()<CR>
au BufEnter * call WithHobbies()
au TextChanged * exec ":call Auto_save()"
au InsertLeave * write
vnoremap E :call Comment()<CR>
let mapleader = "-"
nnoremap <leader>e :find $MYVIMRC<CR>
nnoremap <leader>- :set paste!<CR>
call vundle#end()
